#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstring>
#include <ctime>
#include <complex>

 
using namespace std;
 
typedef vector<int> vi;
typedef vector<string> vs;
typedef long long ll;
typedef complex<int> pnt;
typedef pair<int, int> pii;

#define FOR(i,a,b) for(i=a;i<b;i++) 
#define RA(x) (x).begin(), (x).end()
#define REV(x) reverse(RA(x))
#define FE(i, x) for (typeof((x).begin()) i = (x).begin(); i != (x).end(); i++)
#define SZ(x) ((int) (x).size())
#define X first
#define Y second

int end[55], dp[55];
class ContestSchedule {
public:
	double expectedWinnings(vector <string> c){
		int i, j, s, t, w, n = SZ(c), mx = 0;
		memset(dp, 0, sizeof dp);
		FOR(i, 0, n){
			sscanf(c[i].c_str(), "%d %d %d", &s, &t, &w);
			end[i] = t;
			mx = 0;
			FOR(j, 0, i){
				if(s >= end[j]){
					mx = max(dp[j], mx);
				}
			}
			dp[i] = max(mx+w, dp[i]);
		}
		mx = 0;
		FOR(i, 0, 55){
			mx = max(mx, dp[i]);
		}
		return mx*1.0/100;
	} 
};

 
// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, double p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	ContestSchedule *obj;
	double answer;
	obj = new ContestSchedule();
	clock_t startTime = clock();
	answer = obj->expectedWinnings(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = fabs(p1 - answer) <= 1e-9 * max(1.0, fabs(p1));
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	double p1;
	
	{
	// ----- test 0 -----
	string t0[] = ;
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 4.0;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"10 20 20","30 40 60","15 35 90"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0.9;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"1 100 85","99 102 100","101 200 60"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1.45;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"1 1000000000 1"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0.01;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"1361955 8940967 10","628145516 644285978 17","883515280 910484865 36","762888635 769291174 52","98152102 136328674 1","9580638 20450682 50","646139319 664648341 20","484027666 505290970 57","841082555 879295329 99","940563715 966953344 4","579113528 595261527 25","925801172 962952912 9","285845005 307916055 45","403573723 410697485 10","9467290 25698952 90","631265400 650639733 3","520690249 559261759 96","491747709 531061081 86","643215695 672420161 94","614608448 617341712 44","456517316 491770747 24","806956091 828414045 88","528156706 559510719 15","158398859 190439269 4","743974602 761975244 49","882264704 887725893 1","877444309 884479317 59","785986538 806192822 19","732553407 747696021 81","132099860 148305810 97","555144412 572785730 99","506507263 535927950 82","489726669 505160939 90","793692316 804153358 99","901329638 919179990 10","29523791 44318662 58","570497239 595701008 73","706091347 730328348 23","118054686 135301010 39","307178252 337804001 93","896162463 900667971"
			" 39","271356542 273095245 80","865692962 891795950 91","593986003 596160000 58","807688147 831190344 59","468916697 496462595 92"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 14.12;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
 

		

//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
