import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;


public class InputBoxChecker
{
	public String[] checkPrefix(int a, int b, int[] arr)
	{
		String[] ans = new String[arr.length];
		for(int i = 0; i < arr.length; i++)
			ans[i] = "INVALID";		
		for(int i = 0; i < arr.length; i++){
			long mx = arr[i], mn = arr[i];
			for(int j = 0; j < 10; j++){
				if(mn <= b && mx >= a){
					ans[i] = "VALID";
				}
				mx *= 10; mx += 9;
				mn *= 10;
			}
		}
		return ans;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int p0, int p1, int[] p2, boolean hasAnswer, String[] p3) {
		System.out.print("Test " + testNum + ": [" + p0 + "," + p1 + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}");
		System.out.println("]");
		InputBoxChecker obj;
		String[] answer;
		obj = new InputBoxChecker();
		long startTime = System.currentTimeMillis();
		answer = obj.checkPrefix(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p3.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p3[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p3.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p3[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int p0;
		int p1;
		int[] p2;
		String[] p3;
		
		// ----- test 0 -----
		p0 = 300;
		p1 = 347;
		p2 = new int[]{37};
		p3 = new String[]{"INVALID"};
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 310;
		p1 = 320;
		p2 = new int[]{3,31,317,3174,310,320};
		p3 = new String[]{"VALID","VALID","VALID","INVALID","VALID","VALID"};
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 600;
		p1 = 1020;
		p2 = new int[]{7,73,734,7349};
		p3 = new String[]{"VALID","VALID","VALID","INVALID"};
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 64;
		p1 = 78;
		p2 = new int[]{1,2,3,4,5,6,7,8,9};
		p3 = new String[]{"INVALID","INVALID","INVALID","INVALID","INVALID","VALID","VALID","INVALID","INVALID"};
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = 1;
		p1 = 1234567890;
		p2 = new int[]{123,456,789,1234567,7654321,3245354,325432532,243212};
		p3 = new String[]{"VALID","VALID","VALID","VALID","VALID","VALID","VALID","VALID"};
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
